# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deployMaster:
    docker:
      - image: circleci/php:7.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # install sshpass
      - run:
          name: install sshpass
          command: |
            sudo apt-get install sshpass
      # changing perssion
      - run: chmod +x ./.circleci/deployMaster.sh
      # deploy and start server
      - run: ./.circleci/deployMaster.sh
  deployDev:
    docker:
      - image: circleci/php:7.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # install sshpass
      - run:
          name: install sshpass
          command: |
            sudo apt-get install sshpass
      # changing perssion
      - run: chmod +x ./.circleci/deployDev.sh
      # deploy and start server
      - run: ./.circleci/deployDev.sh
workflows:
  version: 2
  build_deploy:
    jobs:
      - deployMaster:
          filters:
            branches:
              only: master
      - deployDev:
          filters:
            branches:
              only: development